// scripts/build.js — injects Supabase credentials from env into config.js
// Run automatically by Vercel at deploy time, or locally via `npm run build`

const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
} catch (_) {}

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const profileAEmail = process.env.PROFILE_A_EMAIL || '';
const profileAPassword = process.env.PROFILE_A_PASSWORD || '';
const profileBEmail = process.env.PROFILE_B_EMAIL || '';
const profileBPassword = process.env.PROFILE_B_PASSWORD || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[chairside] Warning: SUPABASE_URL or SUPABASE_ANON_KEY not set.\n' +
    '  The app will run without Supabase.\n' +
    '  See .env.example for setup instructions.'
  );
}

const out = `// config.js — auto-generated by scripts/build.js (do not edit manually)
window.CHAIRSIDE_CONFIG = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
  profileAEmail: ${JSON.stringify(profileAEmail)},
  profileAPassword: ${JSON.stringify(profileAPassword)},
  profileBEmail: ${JSON.stringify(profileBEmail)},
  profileBPassword: ${JSON.stringify(profileBPassword)},
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'config.js'), out, 'utf8');
console.log('[chairside] config.js generated.');
