// scripts/build.js — injects Supabase credentials from env into config.js
// Run automatically by Vercel at deploy time, or locally via `npm run build`

const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
} catch (_) {}

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[chairside] Warning: SUPABASE_URL or SUPABASE_ANON_KEY not set.\n' +
    '  The app will run in demo mode with mock data.\n' +
    '  See .env.example for setup instructions.'
  );
}

const out = `// config.js — auto-generated by scripts/build.js (do not edit manually)
// Set SUPABASE_URL and SUPABASE_ANON_KEY in your environment or .env file.
window.CHAIRSIDE_CONFIG = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
};
`;

fs.writeFileSync(path.join(__dirname, '..', 'config.js'), out, 'utf8');
console.log('[chairside] config.js generated.');
